services:
  influxdb1-src:
    image: influxdb:1.8
    container_name: influxdb1-src-1x3x
    ports:
      - "18086:8086"
    environment:
      - INFLUXDB_DB=testdb
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # InfluxDB 3.x 使用 InfluxDB Edge 作为测试环境
  # 注意：InfluxDB 3.x 目前主要以云服务形式提供，这里使用 2.x 模拟 v2 兼容模式
  influxdb3-dst:
    image: influxdb:2.7
    container_name: influxdb3-dst-1x3x
    ports:
      - "18088:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=testorg
      - DOCKER_INFLUXDB_INIT_BUCKET=testbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=test3xtoken
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    name: influxdb-sync-test-1x3x
