version: "3.8"
services:
  influxdb1-src:
    image: influxdb:1.8
    container_name: influxdb1-src
    ports:
      - "18086:8086"
    environment:
      - INFLUXDB_DB=testdb
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
  influxdb2-dst:
    image: influxdb:2.7
    container_name: influxdb2-dst
    ports:
      - "18087:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=testorg
      - DOCKER_INFLUXDB_INIT_BUCKET=testbucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=testtoken
