# 源和目标都支持 type: 1（InfluxDB 1.x）或 type: 2（InfluxDB 2.x）

source:
  type: 1
  url: "http://localhost:18086"
  user: "admin"
  pass: "admin123"
  db: "testdb"
  token: ""
  org: ""
  bucket: ""

target:
  type: 1
  url: "http://localhost:18087"
  user: "admin"
  pass: "admin123"
  db: "testdb"
  token: ""
  org: ""
  bucket: ""

sync:
  start: "2024-01-01T00:00:00Z"
  end: "2025-01-01T00:00:00Z"
  batch_size: 10000
  resume_file: "resume.state"
