# InfluxDB 1.x 到 3.x 同步配置示例
# 源数据库 - InfluxDB 1.x
source:
  type: 1 # 1 表示 InfluxDB 1.x
  url: "http://localhost:8086" # InfluxDB 1.x 服务地址
  user: "admin" # 用户名
  pass: "password" # 密码
  db: "mydb" # 数据库名称，留空表示同步所有数据库
  db_exclude: ["_internal"] # 排除的数据库列表

# 目标数据库 - InfluxDB 3.x (v2 兼容模式)
target:
  type: 3 # 3 表示 InfluxDB 3.x
  url: "http://localhost:8086" # InfluxDB 3.x 服务地址
  token: "your-v2-token-here" # v2 兼容 API Token
  org: "my-org" # 组织名称
  database: "mydb" # 目标数据库/bucket 名称
  compat_mode: "v2" # 兼容模式：v2
  db_prefix: "" # 数据库名前缀
  db_suffix: "" # 数据库名后缀

# 同步配置
sync:
  start: "" # 开始时间 (RFC3339 格式，如 2023-01-01T00:00:00Z)，留空表示从最早开始
  end: "" # 结束时间 (RFC3339 格式)，留空表示到最新
  batch_size: 5000 # 批量大小
  resume_file: "resume_1x3x.json" # 断点续传文件
  parallel: 4 # 并行度
  retry_count: 3 # 重试次数
  retry_interval: 5 # 重试间隔（秒）
  rate_limit: 1000 # 速率限制（点/秒）

# 日志配置
log:
  level: "info" # 日志级别：debug, info, warn, error
