# InfluxDB 1.x 到 3.x 本地测试配置
# 源数据库 - InfluxDB 1.x
source:
  type: 1 # 1 表示 InfluxDB 1.x
  url: "http://localhost:18086" # docker-compose 中的 1.x 端口
  user: "admin" # 用户名
  pass: "admin123" # 密码
  db: "testdb" # 数据库名称

# 目标数据库 - InfluxDB 3.x (v2 兼容模式)
target:
  type: 3 # 3 表示 InfluxDB 3.x
  url: "http://localhost:18088" # docker-compose 中的 3.x 端口
  token: "test3xtoken" # v2 兼容 API Token
  org: "testorg" # 组织名称
  database: "testbucket" # 目标数据库/bucket 名称
  compat_mode: "v2" # 兼容模式：v2

# 同步配置
sync:
  start: "" # 开始时间，留空表示从最早开始
  end: "" # 结束时间，留空表示到最新
  batch_size: 1000 # 批量大小
  resume_file: "resume_test_1x3x.json" # 断点续传文件
  parallel: 2 # 并行度
  retry_count: 3 # 重试次数
  retry_interval: 5 # 重试间隔（秒）
  rate_limit: 500 # 速率限制（点/秒）

# 日志配置
log:
  level: "debug" # 测试时使用 debug 级别
