version: "3"
tasks:
  build:
    desc: 构建二进制文件
    cmds:
      - go build -o influxdb-sync main.go
  run:
    desc: 运行主程序
    cmds:
      - go run main.go
  tidy:
    desc: 整理依赖
    cmds:
      - go mod tidy
  clean:
    desc: 清理构建产物
    cmds:
      - rm -f influxdb-sync

  test-1x-1x:
    desc: 一键测试 1.x->1.x 同步
    cmds:
      - docker-compose -f deployments/docker-compose-1x-1x.yml up -d
      - sleep 5
      - bash scripts/write_data_1x.sh
      - sleep 2
      - go run main.go config.yaml
      - |
        bash scripts/query_data_1x.sh
        if grep -q "差异: [1-9][0-9]* 条" <(bash scripts/query_data_1x.sh); then
          echo "数据校验失败，请人工排查！"
          exit 1
        else
          docker-compose -f deployments/docker-compose-1x-1x.yml down
        fi

  test-1x-2x:
    desc: 一键测试 1.x->2.x 同步
    cmds:
      - docker-compose -f deployments/docker-compose-1x-2x.yml up -d
      - sleep 8
      - bash scripts/write_data_1x.sh
      - sleep 2
      - go run main.go config.yaml
      - |
        bash scripts/query_data_2x.sh
        if grep -q "差异: [1-9][0-9]* 条" <(bash scripts/query_data_2x.sh); then
          echo "数据校验失败，请人工排查！"
          exit 1
        else
          docker-compose -f deployments/docker-compose-1x-2x.yml down
        fi

  test-2x-2x:
    desc: 一键测试 2.x->2.x 同步
    cmds:
      - docker-compose -f deployments/docker-compose-2x-2x.yml up -d
      - sleep 8
      - bash scripts/write_data_2x.sh
      - sleep 2
      - go run main.go config.yaml
      - |
        bash scripts/query_data_2x.sh
        if grep -q "差异: [1-9][0-9]* 条" <(bash scripts/query_data_2x.sh); then
          echo "数据校验失败，请人工排查！"
          exit 1
        else
          docker-compose -f deployments/docker-compose-2x-2x.yml down
        fi
